export const constants = {
  randomColors: [
    "#c2a344",
    "#b45ac2",
    "#6cb643",
    "#7178ca",
    "#677c37",
    "#cd4063",
    "#55b280",
    "#c06a94",
    "#4bafd0",
    "#c8683f",
  ],
  dropdownKeys: ["term_desc", "level_desc", "student_type", "online"],
  yAxisOptions: ["each_day", "daily_change", "melt"],
  totalKeys: ["_FREQ_", "Official"],
  xAxisKeys: ["days", "date"],
  yAxisLabel: "enrollment",
  groupByKey: "term_desc",
  url: "Data/data.csv",
  dateKeys: ["date"],
  yAxisKey: "_FREQ_",
};
